FROM python:3.9

WORKDIR /app

# Avoid permission errors
ENV STREAMLIT_BROWSER_GATHERUSAGESTATS=false
ENV STREAMLIT_CONFIG_HOME=/app/.streamlit

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7860

CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0"]
